GH-6 Adds libfcgi0ldbl to test FPM directly

diff --git a/test b/test
--- a/test
+++ b/test
@@ -23,10 +23,25 @@ EOF
     exit 1
 fi
 
+run_fpm_container() {
+    ENVFLAG=""
+    if [ ! -z "${1:-}" ]; then
+        ENVFLAG="-e ${1:-}"
+    fi
+
+    docker container run -d --name jtreminio_test \
+        -v ${PWD}/files/index.php:/var/www/index.php \
+        ${ENVFLAG} \
+        ${IMAGE} > /dev/null 2>&1
+}
+
+rm_fpm_container() {
+    docker container rm -f jtreminio_test > /dev/null 2>&1
+}
 
 printf "Testing ${IMAGE}\n\n"
 
-printf "Check version correct"
+printf "[CLI] Check version correct"
 EXPECTS="PHP ${PHP_VERSION}"
 CMD=$(cat << EOF
 docker container run --rm \
@@ -41,9 +56,28 @@ else
     printf " ${PASS}"
 fi
 
+printf "[FPM] Check version correct"
+EXPECTS="PHP Version ${PHP_VERSION}"
+CMD=$(cat << EOF
+docker container exec \
+    jtreminio_test bash -c "SCRIPT_FILENAME=/var/www/index.php \
+        REQUEST_METHOD=GET \
+        cgi-fcgi -bind -connect 127.0.0.1:9000"
+EOF
+)
+run_fpm_container
+RESULT=$(bash -c "${CMD}" | grep -c "${EXPECTS}")
+rm_fpm_container
+if [ ${RESULT} -ne 1 ]; then
+    printf " ${FAIL}"
+    exit 1
+else
+    printf " ${PASS}"
+fi
+
 ###
 
-printf "Check custom INI loaded"
+printf "[CLI] Check custom INI loaded"
 EXPECTS="/etc/php/${PHP_VERSION}/cli/conf.d/98-env.ini"
 CMD=$(cat << EOF
 docker container run --rm \
@@ -58,9 +92,64 @@ else
     printf " ${PASS}"
 fi
 
+printf "[FPM] Check custom INI loaded"
+EXPECTS="/etc/php/${PHP_VERSION}/fpm/conf.d/98-env.ini"
+CMD=$(cat << EOF
+docker container exec \
+    jtreminio_test bash -c "SCRIPT_FILENAME=/var/www/index.php \
+        REQUEST_METHOD=GET \
+        cgi-fcgi -bind -connect 127.0.0.1:9000"
+EOF
+)
+run_fpm_container
+RESULT=$(bash -c "${CMD}" | grep -c "${EXPECTS}")
+rm_fpm_container
+if [ ${RESULT} -ne 1 ]; then
+    printf " ${FAIL}"
+    exit 1
+else
+    printf " ${PASS}"
+fi
+
 ###
 
-printf "Check display_errors set to default value"
+printf "[CLI] Check FPM INI not loaded"
+EXPECTS="/etc/php/${PHP_VERSION}/fpm/conf.d/98-env.ini"
+CMD=$(cat << EOF
+docker container run --rm \
+  ${IMAGE} bash -c "php --ini"
+EOF
+)
+RESULT=$(bash -c "${CMD}" | grep -c "${EXPECTS}")
+if [ ${RESULT} -ne 0 ]; then
+    printf " ${FAIL}"
+    exit 1
+else
+    printf " ${PASS}"
+fi
+
+printf "[FPM] Check CLI INI not loaded"
+EXPECTS="/etc/php/${PHP_VERSION}/cli/conf.d/98-env.ini"
+CMD=$(cat << EOF
+docker container exec \
+    jtreminio_test bash -c "SCRIPT_FILENAME=/var/www/index.php \
+        REQUEST_METHOD=GET \
+        cgi-fcgi -bind -connect 127.0.0.1:9000"
+EOF
+)
+run_fpm_container
+RESULT=$(bash -c "${CMD}" | grep -c "${EXPECTS}")
+rm_fpm_container
+if [ ${RESULT} -ne 0 ]; then
+    printf " ${FAIL}"
+    exit 1
+else
+    printf " ${PASS}"
+fi
+
+###
+
+printf "[CLI] Check display_errors set to default value"
 EXPECTS="display_errors => Off => Off"
 CMD=$(cat << EOF
 docker container run --rm \
@@ -75,9 +164,28 @@ else
     printf " ${PASS}"
 fi
 
+printf "[FPM] Check display_errors set to default value"
+EXPECTS="display_errors</td><td class=\"v\">Off"
+CMD=$(cat << EOF
+docker container exec \
+    jtreminio_test bash -c "SCRIPT_FILENAME=/var/www/index.php \
+        REQUEST_METHOD=GET \
+        cgi-fcgi -bind -connect 127.0.0.1:9000"
+EOF
+)
+run_fpm_container
+RESULT=$(bash -c "${CMD}" | grep -c "${EXPECTS}")
+rm_fpm_container
+if [ ${RESULT} -ne 1 ]; then
+    printf " ${FAIL}"
+    exit 1
+else
+    printf " ${PASS}"
+fi
+
 ###
 
-printf "Check display_errors accepts override value"
+printf "[CLI] Check display_errors accepts override value"
 EXPECTS="display_errors => STDOUT => STDOUT"
 CMD=$(cat << EOF
 docker container run --rm \
@@ -93,9 +201,28 @@ else
     printf " ${PASS}"
 fi
 
+printf "[FPM] Check display_errors accepts override value"
+EXPECTS="display_errors</td><td class=\"v\">On"
+CMD=$(cat << EOF
+docker container exec \
+    jtreminio_test bash -c "SCRIPT_FILENAME=/var/www/index.php \
+        REQUEST_METHOD=GET \
+        cgi-fcgi -bind -connect 127.0.0.1:9000"
+EOF
+)
+run_fpm_container "PHP_DISPLAY_ERRORS=1"
+RESULT=$(bash -c "${CMD}" | grep -c "${EXPECTS}")
+rm_fpm_container
+if [ ${RESULT} -ne 1 ]; then
+    printf " ${FAIL}"
+    exit 1
+else
+    printf " ${PASS}"
+fi
+
 ###
 
-printf "Check Xdebug not loaded by default"
+printf "[CLI] Check Xdebug not loaded by default"
 EXPECTS="with Xdebug"
 CMD=$(cat << EOF
 docker container run --rm \
@@ -110,9 +237,28 @@ else
     printf " ${PASS}"
 fi
 
+printf "[FPM] Check Xdebug not loaded by default"
+EXPECTS="with Xdebug"
+CMD=$(cat << EOF
+docker container exec \
+    jtreminio_test bash -c "SCRIPT_FILENAME=/var/www/index.php \
+        REQUEST_METHOD=GET \
+        cgi-fcgi -bind -connect 127.0.0.1:9000"
+EOF
+)
+run_fpm_container
+RESULT=$(bash -c "${CMD}" | grep -c "${EXPECTS}")
+rm_fpm_container
+if [ ${RESULT} -ne 0 ]; then
+    printf " ${FAIL}"
+    exit 1
+else
+    printf " ${PASS}"
+fi
+
 ###
 
-printf "Check Xdebug loaded by env var"
+printf "[CLI] Check Xdebug loaded by env var"
 EXPECTS="with Xdebug"
 CMD=$(cat << EOF
 docker container run --rm \
@@ -128,9 +274,28 @@ else
     printf " ${PASS}"
 fi
 
+printf "[FPM] Check Xdebug loaded by env var"
+EXPECTS="with&nbsp;Xdebug"
+CMD=$(cat << EOF
+docker container exec \
+    jtreminio_test bash -c "SCRIPT_FILENAME=/var/www/index.php \
+        REQUEST_METHOD=GET \
+        cgi-fcgi -bind -connect 127.0.0.1:9000"
+EOF
+)
+run_fpm_container "PHP_INI_SCAN_DIR=:/etc/php/conf-env/xdebug"
+RESULT=$(bash -c "${CMD}" | grep -c "${EXPECTS}")
+rm_fpm_container
+if [ ${RESULT} -ne 1 ]; then
+    printf " ${FAIL}"
+    exit 1
+else
+    printf " ${PASS}"
+fi
+
 ###
 
-printf "Check xdebug.remote_host set to default value"
+printf "[CLI] Check xdebug.remote_host set to default value"
 EXPECTS="xdebug.remote_host => host.docker.internal => host.docker.internal"
 CMD=$(cat << EOF
 docker container run --rm \
@@ -148,16 +313,58 @@ fi
 
 ###
 
-printf "Check xdebug.remote_host accepts override value"
-EXPECTS="xdebug.remote_host => 172.17.0.1 => 172.17.0.1"
+printf "[FPM] Check xdebug.remote_host set to default value"
+EXPECTS="xdebug.remote_host</td><td class=\"v\">host.docker.internal"
+CMD=$(cat << EOF
+docker container exec \
+    jtreminio_test bash -c "SCRIPT_FILENAME=/var/www/index.php \
+        REQUEST_METHOD=GET \
+        cgi-fcgi -bind -connect 127.0.0.1:9000"
+EOF
+)
+run_fpm_container "PHP_INI_SCAN_DIR=:/etc/php/conf-env/xdebug"
+RESULT=$(bash -c "${CMD}" | grep -c "${EXPECTS}")
+rm_fpm_container
+if [ ${RESULT} -ne 1 ]; then
+    printf " ${FAIL}"
+    exit 1
+else
+    printf " ${PASS}"
+fi
+
+###
+
+printf "[CLI] Check xdebug.remote_host accepts overriden value"
+EXPECTS="xdebug.remote_host => custom.localhost => custom.localhost"
 CMD=$(cat << EOF
 docker container run --rm \
   -e PHP_INI_SCAN_DIR=:/etc/php/conf-env/xdebug \
-  -e XDEBUG_REMOTE_HOST=172.17.0.1 \
+  -e XDEBUG_REMOTE_HOST=custom.localhost \
   ${IMAGE} bash -c "php -i"
 EOF
 )
 RESULT=$(bash -c "${CMD}" | grep -c "${EXPECTS}")
+if [ ${RESULT} -ne 1 ]; then
+    printf " ${FAIL}"
+    exit 1
+else
+    printf " ${PASS}"
+fi
+
+###
+
+printf "[FPM] Check xdebug.remote_host accepts overriden value"
+EXPECTS="xdebug.remote_host</td><td class=\"v\">custom.localhost"
+CMD=$(cat << EOF
+docker container exec \
+    jtreminio_test bash -c "SCRIPT_FILENAME=/var/www/index.php \
+        REQUEST_METHOD=GET \
+        cgi-fcgi -bind -connect 127.0.0.1:9000"
+EOF
+)
+run_fpm_container "PHP_INI_SCAN_DIR=:/etc/php/conf-env/xdebug -e XDEBUG_REMOTE_HOST=custom.localhost"
+RESULT=$(bash -c "${CMD}" | grep -c "${EXPECTS}")
+rm_fpm_container
 if [ ${RESULT} -ne 1 ]; then
     printf " ${FAIL}"
     exit 1
